version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    restart: on-failure
    ports:
      - 3000:3000
    platform: linux/x86_64
    depends_on:
      - backend
  
  backend:
    container_name: app_backend
    build: ./backend
    restart: 'always'
    ports:
      - 3001:3001
    platform: linux/x86_64
    environment:
      - JWT_SECRET=jwt_secret
      - MONGO_URI=mongodb://db:27017/
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo_db
    platform: linux/arm64/v8
    ports:
      - 27017:27017
    restart: 'always'
